apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: "/data"
          name: grafana-storage
  volumes:
    - name: grafana-storage
      persistentVolumeClaim:
        claimName: prometheus-stack-grafana
