apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv 
spec:
  capacity:
    storage: 1Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: gp3-sc
  awsElasticBlockStore:
    volumeID: vol-05c647fa3b92a2000
    fsType: ext4  
