apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-stack-grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-sc 
  resources:
    requests:
      storage: 1Gi 
