apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      serviceAccountName: prometheus-thanos-sa
      containers:
      - name: thanos-store
        image: quay.io/thanos/thanos:v0.28.1
        args:
          - store
          - --data-dir=/data
          - --objstore.config-file=/etc/thanos/object-store.yaml
          - --index-cache-size=500MB
          - --chunk-pool-size=2GB
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        volumeMounts:
          - name: thanos-config
            mountPath: /etc/thanos
            readOnly: true
      volumes:
        - name: thanos-config
          secret:
            secretName: thanos
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store
spec:
  selector:
    app: thanos-store
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
    - name: http
      port: 10902
      targetPort: 10902
  type: ClusterIP