all:
 vars:
   ansible_user: ubuntu
   ansible_ssh_private_key_file: /Users/sauravsingh/Downloads/saurav-mumbai.pem
   
 children:
   master:
     hosts:
       master-server:
         ansible_host: 65.1.108.254
         
   clients:
     hosts:
       client-server-1:
         ansible_host: 172.31.15.211
         ansible_ssh_common_args: '-o ProxyCommand="ssh -i /Users/sauravsingh/Downloads/saurav-mumbai.pem -W %h:%p ubuntu@65.1.108.254"'
       
       client-server-2:
         ansible_host: 172.31.10.233
         ansible_ssh_common_args: '-o ProxyCommand="ssh -i /Users/sauravsingh/Downloads/saurav-mumbai.pem -W %h:%p ubuntu@65.1.108.254"'
       
       client-server-3:
         ansible_host: 172.31.4.62
         ansible_ssh_common_args: '-o ProxyCommand="ssh -i /Users/sauravsingh/Downloads/saurav-mumbai.pem -W %h:%p ubuntu@65.1.108.254"'