apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      serviceAccountName: prometheus-thanos-sa
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.28.1
        args:
          - query
          - --grpc-address=0.0.0.0:10901
          - --http-address=0.0.0.0:10902
          - --store=thanos-store:10901
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
spec:
  selector:
    app: thanos-query
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
    - name: http
      port: 10902
      targetPort: 10902
  type: ClusterIP
